// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int big = 0;
		int small = 0;

		for (int n = 0; n < N; n++) {
			if (Math.random() > 0.5) big++; 
			 else {
				small++;
			 }

		}
		double ratio = (double) big/small ;
		System.out.println("> 0.5: " + big + " times");
		System.out.println("<= 0.5: " + small + " times" );
		if (small != 0) System.out.println("Ratio: " + ratio);
	}
}
